### ISSUE TITLE
Android SDK missing

### ISSUE THREAD

**Issue by FabricioCabeca** [Mofiler/sdks#1]
Hi there, just noticed the link to the Android SDK is broken.

**Comment by btafel** [comment]
Hi Fabricio! You need to be added as a collaborator to access that repository. I'm adding you now, please try again.

**Comment by FabricioCabeca** [comment]
Thanks ! I was worried about some beacon service issues but it seems like you have already disabled it in the current version.

**Comment by btafel** [comment]
Yes, we found that Beacons data was worth only for just a few specific cases, so we decided to take it out. But the code is there in case we decide to add it again. Let me know if you have any doubts/thoughts!
